### ISSUE TITLE
[Bug]: Shopify app dev not working

### ISSUE THREAD

**Issue by devcrazygit** [Shopify/cli#1149]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

I created shopify app using the shopify app node template (https://github.com/Shopify/shopify-app-template-node)
I ran `npm install` and all the packages are installed.
Run `npm run dev` 
While running this command, I logged in and set the app name and choose the development store correctly

But the next is the problem, it should run the shopify app, but not works

OS is win 10.

package.json is
```
{
  "name": "my-node-app",
  "version": "1.0.0",
  "main": "web/index.js",
  "license": "UNLICENSED",
  "scripts": {
    "shopify": "shopify",
    "build": "shopify app build",
    "dev": "shopify app dev",
    "info": "shopify app info",
    "generate": "shopify app generate",
    "deploy": "shopify app deploy"
  },
  "dependencies": {
    "@shopify/app": "^3.0.0",
    "@shopify/cli": "^3.0.0"
  }
}

```

### Actual behavior

It returns error with this message

`✖ Command failed with exit code 6: npm install`

### Stack trace

```shell
$ npm run dev

> my-node-app@1.0.0 dev
> shopify app dev


Using your previous dev settings:
- Org:          [My Shop]
- App:          [App name]
- Dev store:    [myshop].myshopify.com
- Update URLs:  Not yet configured

To reset your default dev config, run npm run dev -- --reset

✖ Command failed with exit code 6: npm install
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm ERR! code 6
npm ERR! path F:\test\b…

── external error ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Error coming from `npm install`

Command failed with exit code 6: npm install
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm ERR! code 6
npm ERR! path F:\test\bb\web\node_modules\sqlite3
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.10
npm ERR! node-pre-gyp info using node@16.14.0 | win32 | x64
npm ERR! node-pre-gyp info check checked for "F:\test\bb\web\node_modules\sqlite3\lib\binding\napi-v6-win32-unknown-x64\node_sqlite3.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/TryGhost/node-sqlite3/releases/download/v5.1.4/napi-v6-win32-unknown-x64.tar.gz
npm ERR! node-pre-gyp info install unpacking napi-v6-win32-unknown-x64/node_sqlite3.node
npm ERR! node-pre-gyp ERR! Completion callback never invoked!
npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.19044
npm ERR! node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "F:\\test\\bb\\web\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"npm ERR! node-pre-gyp ERR! cwd F:\test\bb\web\node_modules\sqlite3
npm ERR! node-pre-gyp ERR! node -v v16.14.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.10

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user1\AppData\Local\npm-cache\_logs\2023-01-19T04_20_37_910Z-debug-0.log

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

F:\test\bb\node_modules\yoga-layout-prebuilt\yoga-layout\build\Release\nbind.js:53
        throw ex;
        ^

Abort [Error]: Failed to kill process 15720: Error: Command failed: taskkill /pid 15720 /T /F
ERROR: The process "15720" not found.

    at file:///F:/test/bb/node_modules/@shopify/cli-kit/dist/public/node/system.js:48:27
    at ChildProcess.exithandler (node:child_process:406:5)
    at ChildProcess.emit (node:events:520:28)
    at ChildProcess.emit (node:domain:475:12)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  tryMessage: null,
  type: 0,
  nextSteps: undefined
}
```

### Reproduction steps

1.
2.
3.

### Operating System

Windows 10

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.34.0

### Shell

Git Bash

### Node version (run `node -v` if you're not sure)

16.14.0

### What language and version are you using in your application?

Node 16.14.0

**Comment by devcrazygit** [comment]
`npm i` is succeeded already
But when I run `dev` then cli shows the following (I don't know why it is trying to dependencies here) and finally failed like above.

```
$ npm run dev

> my-node-app@1.0.0 dev
> shopify app dev


Using your previous dev settings:
- Org:          [Shop org]
- App:          [App Name]
- Dev store:    [shop_name].myshopify.com
- Update URLs:  Not yet configured

To reset your default dev config, run npm run dev -- --reset

⠧ Installing any necessary dependencies
```

**Comment by amcaplan** [comment]
@devcrazygit have you tried running `npm run dev --skip-dependencies-installation`? Might help see if everything is working, or perhaps there's a part of the project with its own `package.json` where things aren't installing properly.

**Comment by matteodepalo** [comment]
Could you try again with the latest version? We've fixed some issues with `dev` and theme app extensions which might have affected this.

**Comment by federicobenedetti** [comment]
Seems to be working fine now, i can't reproduce the error. Thanks!

**Comment by StephenChris91** [comment]
Hi, 

After opening this issue, i proceeded to installing python and gyp.

However, the problem still persists.

**Comment by amcaplan** [comment]
@StephenChris91 this is happening as the CLI attempts to install dependencies for your project. Something isn't working there, though. You can skip the step using the `--skip-dependencies-install` flag, and see if it works. You should also try running `npm install` in your web directories and see whether it works or doesn't work.

This isn't related to the original issue, so I'd recommend opening a new issue. This issue is already closed anyway. In the meantime, I'll lock the current issue, as this isn't the right place to discuss.
