### ISSUE TITLE
[Bug]: Generated Theme App Extension does not appear in theme editor

### ISSUE THREAD

**Issue by sneakingJ** [Shopify/cli#1945]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

```
yarn shopify app generate extension
yarn dev --tunnel ngrok
```
Clicking on the theme editor link from the CLI output should provide the option to add the generated Star Rating block, right?

### Actual behavior

Everything seems to work fine. No errors pop up and I can enable the theme app extension in the app settings with the first link provided by the CLI output.
The second link leads me to the them editor, which also seems to open correctly but I can't add the Star Rating block. Where is it supposed to be or am I missing something?
Basically all I did was follow the instructions in https://shopify.dev/docs/apps/online-store/theme-app-extensions/getting-started and then running `yarn dev`.

### Verbose output

```shell
yarn run v1.22.10
$ shopify app dev --tunnel ngrok --verbose
2023-05-16T17:11:57.010Z: Running command app dev
2023-05-16T17:11:57.017Z: Ensuring that the user is authenticated with the Partners API with the following scopes:
[]

2023-05-16T17:11:57.019Z: Getting session store...
2023-05-16T17:11:57.020Z: Validating existing session against the scopes:
[
  "openid",
  "https://api.shopify.com/auth/shop.admin.graphql",
  "https://api.shopify.com/auth/shop.admin.themes",
  "https://api.shopify.com/auth/partners.collaborator-relationships.readonly",
  "https://api.shopify.com/auth/shop.storefront-renderer.devtools",
  "https://api.shopify.com/auth/partners.app.cli.access"
]
For applications:
{
  "partnersApi": {
    "scopes": []
  }
}

2023-05-16T17:11:57.021Z: Sending Identity Introspection request to URL: https://accounts.shopify.com/oauth/introspection
2023-05-16T17:11:57.021Z: Sending POST request to URL https://accounts.shopify.com/oauth/introspection
With request headers:
 - User-Agent: Shopify CLI; v=3.45.4
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: linux
 - Content-Type: application/json

2023-05-16T17:11:57.311Z: Request to https://accounts.shopify.com/oauth/introspection completed in 283 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"295b6624a640fb80541b32b45d1d6c43"
 - x-request-id: 3c28fccb-ec1d-48d2-a943-b1cfb6c99a71
    
2023-05-16T17:11:57.321Z: The identity token is valid: true
2023-05-16T17:11:57.322Z: 
The validation of the token for application/identity completed with the following results:
- It's expired: false
- It's invalid in identity: false
  
2023-05-16T17:11:57.323Z: Verifying that the user has a Partner organization
2023-05-16T17:11:57.324Z: Sending "Partners" GraphQL request:
  {
    organizations(first: 1) {
      nodes {
        id
      }
    }
  }

With request headers:
 - User-Agent: Shopify CLI; v=3.45.4
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: linux
 - Content-Type: application/json

2023-05-16T17:11:57.693Z: Request to https://partners.shopify.com/api/cli/graphql completed in 356 ms
With response headers:
 - cache-control: max-age=0, private, must-revalidate
 - content-type: application/json; charset=utf-8
 - etag: W/"2a10696b19a66b4d325e944b79ad3bb5"
 - x-request-id: ec53e706-be27-46f4-a1e4-34b2ee32823a
    
2023-05-16T17:11:57.696Z: Reading cached app information for directory /home/xxx/dev/yyy/src/shopify/cli...
2023-05-16T17:11:57.698Z: Sending "Partners" GraphQL request:
  query FindOrganization($id: ID!) {
    organizations(id: $id, first: 1) {
      nodes {
        id
        businessName
        website
        betas {
          appUiDeployments
          cliTunnelAlternative
        }
      }
    }
  }

With variables:
{
  "id": "xxx"
}

With request headers:
 - User-Agent: Shopify CLI; v=3.45.4
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: linux
 - Content-Type: application/json

2023-05-16T17:11:57.995Z: Request to https://partners.shopify.com/api/cli/graphql completed in 291 ms
With response headers:
 - cache-control: max-age=0, private, must-revalidate
 - content-type: application/json; charset=utf-8
 - etag: W/"14af4f7b817c06242713db3311a3562a"
 - x-request-id: 78aeaa2c-8f48-4cd3-bac2-ad8144bb6a21
    
2023-05-16T17:11:57.996Z: Sending "Partners" GraphQL request:
  query FindApp($apiKey: String!) {
    app(apiKey: $apiKey) {
      id
      title
      apiKey
      organizationId
      apiSecretKeys {
        secret
      }
      appType
      grantedScopes
    }
  }

With variables:
{
  "apiKey": "xxx"
}

With request headers:
 - User-Agent: Shopify CLI; v=3.45.4
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: linux
 - Content-Type: application/json

2023-05-16T17:11:57.997Z: Sending "Partners" GraphQL request:
  query FindOrganization($id: ID!, $shopDomain: String) {
    organizations(id: $id, first: 1) {
      nodes {
        id
        businessName
        website
        betas {
          appUiDeployments
        }
        stores(shopDomain: $shopDomain, first: 1, archived: false) {
          nodes {
            shopId
            link
            shopDomain
            shopName
            transferDisabled
            convertableToPartnerTest
          }
        }
      }
    }
  }

With variables:
{
  "id": "xxxx",
  "shopDomain": "yyy.myshopify.com"
}

With request headers:
 - User-Agent: Shopify CLI; v=3.45.4
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: linux
 - Content-Type: application/json

2023-05-16T17:11:58.323Z: Request to https://partners.shopify.com/api/cli/graphql completed in 319 ms
With response headers:
 - cache-control: max-age=0, private, must-revalidate
 - content-type: application/json; charset=utf-8
 - etag: W/"9242c51f9fcf726ed76a400ac8282c23"
 - x-request-id: c80e0694-c055-42f5-aa53-b907ed1b0b0a
    
2023-05-16T17:11:58.573Z: Request to https://partners.shopify.com/api/cli/graphql completed in 573 ms
With response headers:
 - cache-control: max-age=0, private, must-revalidate
 - content-type: application/json; charset=utf-8
 - etag: W/"0b9d197ff5cd2e099dfa91d188d65903"
 - x-request-id: 7ffa9e76-85e6-492a-9655-b1d288038a89
    
2023-05-16T17:11:58.575Z: Storing app information for directory /home/xxx/dev/yyy/src/shopify/cli:{
  "appId": "xxx",
  "title": "xxx",
  "directory": "/home/xxx/dev/yyy/src/shopify/cli",
  "storeFqdn": "yyy.myshopify.com",
  "orgId": "xxx"
}
2023-05-16T17:11:58.597Z: Obtaining the dependency manager in directory /home/xxx/dev/yyy/src/shopify/cli...
╭─ info ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                                                                       │
│  Using your previous dev settings:                                                                                                                                    │
│                                                                                                                                                                       │
│    • Org:          XXX                                                                                                                                     │
│    • App:          XXX                                                                                                                                     │
│    • Dev store:    xxx.myshopify.com                                                                                                                        │
│    • Update URLs:  Not yet configured                                                                                                                                 │
│                                                                                                                                                                       │
│  To reset your default dev config, run `yarn dev --reset`                                                                                                             │
│                                                                                                                                                                       │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

2023-05-16T17:11:58.717Z: Sending "Partners" GraphQL request:
  query fetchSpecifications($api_key: String!) {
    extensionSpecifications(apiKey: $api_key) {
      name
      externalName
      externalIdentifier
      identifier
      gated
      options {
        managementExperience
        registrationLimit
      }
      features {
        argo {
          surface
        }
      }
    }
  }

With variables:
{
  "api_key": "xxx"
}

With request headers:
 - User-Agent: Shopify CLI; v=3.45.4
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: linux
 - Content-Type: application/json

2023-05-16T17:11:59.078Z: Request to https://partners.shopify.com/api/cli/graphql completed in 360 ms
With response headers:
 - cache-control: max-age=0, private, must-revalidate
 - content-type: application/json; charset=utf-8
 - etag: W/"933208cbcf7dd7318a67a66fa914534e"
 - x-request-id: 7cf2cba1-01ab-4697-997e-5cb82b4dcc3b
    
2023-05-16T17:11:59.143Z: Reading the content of file at shopify.app.toml...
2023-05-16T17:11:59.149Z: Reading the content of file at extensions/tracker-ext/shopify.theme.extension.toml...
2023-05-16T17:11:59.150Z: Reading the content of file at package.json...
2023-05-16T17:11:59.150Z: Reading the content of file at package.json...
2023-05-16T17:11:59.151Z: Obtaining the dependency manager in directory /home/xxx/dev/yyy/src/shopify/cli...
2023-05-16T17:11:59.235Z: Reading the content of file at package.json...
2023-05-16T17:11:59.235Z: Unable to decide project type as no web backend
2023-05-16T17:11:59.276Z: 
Running system process:
  · Command: yarn install
  · Working directory: /home/xxx/dev/yyy/src/shopify/cli


2023-05-16T17:11:59.647Z: Reading the content of file at package.json...
2023-05-16T17:11:59.648Z: Getting a random port...
2023-05-16T17:11:59.650Z: Getting a random port...
2023-05-16T17:11:59.650Z: Sending "Partners" GraphQL request:
  query getApp($apiKey: String!) {
    app(apiKey: $apiKey) {
      applicationUrl
      redirectUrlWhitelist
    }
  }

With variables:
{
  "apiKey": "xxx"
}

With request headers:
 - User-Agent: Shopify CLI; v=3.45.4
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: linux
 - Content-Type: application/json

2023-05-16T17:11:59.653Z: Random port obtained: 46753
2023-05-16T17:11:59.653Z: Random port obtained: 36135
2023-05-16T17:11:59.968Z: Request to https://partners.shopify.com/api/cli/graphql completed in 316 ms
With response headers:
 - cache-control: max-age=0, private, must-revalidate
 - content-type: application/json; charset=utf-8
 - etag: W/"9fd59b4b35a3734f58bc85f562d53c40"
 - x-request-id: 045c3e23-9686-4700-9fd4-c4b4bbb5a1cc
    
tracker-ext (Theme App Extension)
Follow the dev doc instructions by deploying your work as a draft

2023-05-16T17:12:01.026Z: Ensuring that the user is authenticated with the Admin API with the following scopes for the store xxx.myshopify.com:
[]

2023-05-16T17:12:01.027Z: Getting session store...
2023-05-16T17:12:01.029Z: Validating existing session against the scopes:
[
  "openid",
  "https://api.shopify.com/auth/shop.admin.graphql",
  "https://api.shopify.com/auth/shop.admin.themes",
  "https://api.shopify.com/auth/partners.collaborator-relationships.readonly",
  "https://api.shopify.com/auth/shop.storefront-renderer.devtools",
  "https://api.shopify.com/auth/partners.app.cli.access"
]
For applications:
{
  "adminApi": {
    "scopes": [],
    "storeFqdn": "xxx.myshopify.com"
  }
}

2023-05-16T17:12:01.030Z: Sending Identity Introspection request to URL: https://accounts.shopify.com/oauth/introspection
2023-05-16T17:12:01.030Z: Sending POST request to URL https://accounts.shopify.com/oauth/introspection
With request headers:
 - User-Agent: Shopify CLI; v=3.45.4
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: linux
 - Content-Type: application/json

2023-05-16T17:12:01.282Z: Request to https://accounts.shopify.com/oauth/introspection completed in 248 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"295b6624a640fb80541b32b45d1d6c43"
 - x-request-id: 23b88c75-a162-4b87-857a-49d771425701
    
2023-05-16T17:12:01.285Z: The identity token is valid: true
2023-05-16T17:12:01.285Z: 
The validation of the token for application/identity completed with the following results:
- It's expired: false
- It's invalid in identity: false
  
2023-05-16T17:12:01.286Z: Getting host theme...
2023-05-16T17:12:01.651Z: Request to https://xxx.myshopify.com/admin/api/unstable/themes/131218047168.json?fields=id completed in 356 ms
With response headers:
 - content-type: application/json; charset=utf-8
 - x-request-id: a5b943bf-a9a9-4716-af9f-8ed647e6bb30
    
2023-05-16T17:12:01.657Z: Ensuring that the user is authenticated with the Storefront API with the following scopes:
[]

2023-05-16T17:12:01.658Z: Getting session store...
2023-05-16T17:12:01.659Z: Sending "Partners" GraphQL request:
  query allAppExtensionRegistrations($apiKey: String!) {
    app(apiKey: $apiKey) {
      extensionRegistrations {
        id
        uuid
        title
        type
      }
      functions {
        id
        uuid
        title
        type: apiType
      }
    }
  }

With variables:
{
  "apiKey": "xxx"
}

With request headers:
 - User-Agent: Shopify CLI; v=3.45.4
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: linux
 - Content-Type: application/json

2023-05-16T17:12:01.664Z: Validating existing session against the scopes:
[
  "openid",
  "https://api.shopify.com/auth/shop.admin.graphql",
  "https://api.shopify.com/auth/shop.admin.themes",
  "https://api.shopify.com/auth/partners.collaborator-relationships.readonly",
  "https://api.shopify.com/auth/shop.storefront-renderer.devtools",
  "https://api.shopify.com/auth/partners.app.cli.access"
]
For applications:
{
  "storefrontRendererApi": {
    "scopes": []
  }
}

2023-05-16T17:12:01.664Z: Sending Identity Introspection request to URL: https://accounts.shopify.com/oauth/introspection
2023-05-16T17:12:01.665Z: Sending POST request to URL https://accounts.shopify.com/oauth/introspection
With request headers:
 - User-Agent: Shopify CLI; v=3.45.4
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: linux
 - Content-Type: application/json

2023-05-16T17:12:01.907Z: Request to https://accounts.shopify.com/oauth/introspection completed in 239 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"295b6624a640fb80541b32b45d1d6c43"
 - x-request-id: b7047f5f-643d-4832-a5de-f048d6ab9016
    
2023-05-16T17:12:01.909Z: The identity token is valid: true
2023-05-16T17:12:01.909Z: 
The validation of the token for application/identity completed with the following results:
- It's expired: false
- It's invalid in identity: false
  
2023-05-16T17:12:02.153Z: Request to https://partners.shopify.com/api/cli/graphql completed in 489 ms
With response headers:
 - cache-control: max-age=0, private, must-revalidate
 - content-type: application/json; charset=utf-8
 - etag: W/"647a0ad61a0138f1a6fa9ad1f04462dc"
 - x-request-id: 72ca8fff-0aa0-4081-bcec-50c6f666a6a9
    
2023-05-16T17:12:02.189Z: Obtaining the dependency manager in directory /home/xxx/dev/yyy/src/shopify/cli...
2023-05-16T17:12:02.198Z: 
Running system process:
  · Command: ruby -v
  · Working directory: /home/xxx/dev/yyy/src/shopify/cli

2023-05-16T17:12:02.498Z: Request to https://monorail-edge.shopifysvc.com/v1/produce completed in 207 ms
With response headers:
 - x-request-id: c370ef82-a65a-40a1-a1f1-93e29f465411
    
2023-05-16T17:12:02.500Z: Analytics event sent: {
  "command": "app dev",
  "time_start": 1684257117011,
  "time_end": 1684257122160,
  "total_time": 5149,
  "success": true,
  "cli_version": "3.45.4",
  "ruby_version": "2.7.8",
  "node_version": "14.20.0",
  "is_employee": false,
  "uname": "linux amd64",
  "env_ci": false,
  "env_plugin_installed_any_custom": false,
  "env_plugin_installed_shopify": "[\"@shopify/app\",\"@shopify/cli\",\"@shopify/plugin-cloudflare\",\"@shopify/plugin-did-you-mean\",\"@shopify/plugin-ngrok\"]",
  "env_shell": "bash",
  "env_device_id": "6bc06c2efc559ae2f0b411497b493abe843894eb",
  "env_cloud": "localhost",
  "env_package_manager": "yarn",
  "partner_id": xxx,
  "api_key": "xxx",
  "app_extensions_any": true,
  "app_extensions_breakdown": "{\"theme\":1}",
  "app_extensions_count": 1,
  "app_extensions_custom_layout": false,
  "app_extensions_function_any": false,
  "app_extensions_function_count": 0,
  "app_extensions_function_custom_layout": false,
  "app_extensions_theme_any": true,
  "app_extensions_theme_count": 1,
  "app_extensions_theme_custom_layout": false,
  "app_extensions_ui_any": false,
  "app_extensions_ui_count": 0,
  "app_extensions_ui_custom_layout": false,
  "app_name_hash": "xxx",
  "app_path_hash": "xxx",
  "app_scopes": "[\"\"]",
  "app_web_backend_any": false,
  "app_web_backend_count": 0,
  "app_web_custom_layout": false,
  "app_web_frontend_any": false,
  "app_web_frontend_count": 0,
  "env_package_manager_workspaces": false,
  "cmd_dev_tunnel_type": "ngrok",
  "cmd_dev_urls_updated": false,
  "store_fqdn_hash": "xxx",
  "cmd_app_dependency_installation_skipped": false,
  "cmd_app_reset_used": false,
  "cmd_all_launcher": "yarn",
  "cmd_all_topic": "app",
  "cmd_all_plugin": "@shopify/app",
  "cmd_all_verbose": true,
  "cmd_all_path_override": true,
  "cmd_all_path_override_hash": "106994c67bdfec03776f23d9b5fb9347804f42e9",
  "args": "--tunnel ngrok --verbose",
  "app_name": "xxx",
  "store_fqdn": "xxx.myshopify.com",
  "env_plugin_installed_all": "[\"@shopify/app\",\"@shopify/cli\",\"@shopify/plugin-cloudflare\",\"@shopify/plugin-did-you-mean\",\"@shopify/plugin-ngrok\"]",
  "metadata": "{\"extraPublic\":{},\"extraSensitive\":{}}"
}
2023-05-16T17:12:02.543Z: 
Running system process:
  · Command: ruby -v
  · Working directory: /home/xxx/dev/yyy/src/shopify/cli

2023-05-16T17:12:02.653Z: 
Running system process:
  · Command: bundle -v
  · Working directory: /home/xxx/dev/yyy/src/shopify/cli

2023-05-16T17:12:02.871Z: Reading the content of file at node_modules/@shopify/cli-kit/assets/cli-ruby/Gemfile...
2023-05-16T17:12:02.878Z: 
Running system process:
  · Command: bundle config set --local path /home/xxx/.cache/shopify-gems-nodejs
  · Working directory: /home/xxx/dev/yyy/src/shopify/cli/node_modules/@shopify/cli-kit/assets/cli-ruby

2023-05-16T17:12:03.073Z: 
Running system process:
  · Command: bundle config set --local without development:test
  · Working directory: /home/xxx/dev/yyy/src/shopify/cli/node_modules/@shopify/cli-kit/assets/cli-ruby

2023-05-16T17:12:03.269Z: 
Running system process:
  · Command: bundle install
  · Working directory: /home/xxx/dev/yyy/src/shopify/cli/node_modules/@shopify/cli-kit/assets/cli-ruby

2023-05-16T17:12:03.570Z: 
Running system process:
  · Command: bundle exec ruby /home/xxx/dev/yyy/src/shopify/cli/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify extension serve /home/xxx/dev/yyy/src/shopify/cli/extensions/tracker-ext --api-key xxx --extension-id xxx --extension-title tracker-ext --extension-type THEME_APP_EXTENSION --theme 131218047168 --generate-tmp-theme
  · Working directory: /home/xxx/dev/yyy/src/shopify/cli

2023-05-16 17:12:04 │ extensions │ DEBUG POST https://partners.shopify.com/api/cli/graphql with request_id: 86ca4f54-13a3-48dd-af5c-69e96532b3c3
2023-05-16 17:12:04 │ extensions │ DEBUG {"data"=>{"extensionSpecifications"=>[{"name"=>"App Nav Item", "identifier"=>"app_nav_item", "options"=>{"managementExperience"=>"custom"}, "features"=>{"argo"=>nil, {"name"=>"Online Store Nav Item", "identifier"=>"online_store_nav_item", 
                                   "options"=>{"managementExperience"=>"custom"}, "features"=>{"argo"=>nil, {"name"=>"POS Link", "identifier"=>"pos_link", "options"=>{"managementExperience"=>"dashboard"}, "features"=>{"argo"=>nil, {"name"=>"App Link", "identifier"=>"app_link", 
                                   "options"=>{"managementExperience"=>"dashboard"}, "features"=>{"argo"=>nil, {"name"=>"Bulk Action", "identifier"=>"bulk_action", "options"=>{"managementExperience"=>"dashboard"}, "features"=>{"argo"=>nil, {"name"=>"Flow - Action Definition", 
                                   "identifier"=>"flow_action_definition", "options"=>{"managementExperience"=>"dashboard"}, "features"=>{"argo"=>nil, {"name"=>"Flow - Trigger Definition", "identifier"=>"flow_trigger_definition", "options"=>{"managementExperience"=>"dashboard"}, 
                                   "features"=>{"argo"=>nil, {"name"=>"Flow - Trigger Discovery Webhook", "identifier"=>"flow_trigger_discovery_webhook", "options"=>{"managementExperience"=>"dashboard"}, "features"=>{"argo"=>nil, {"name"=>"Privacy Compliance Webhooks", 
                                   "identifier"=>"privacy_compliance_webhooks", "options"=>{"managementExperience"=>"custom"}, "features"=>{"argo"=>nil, {"name"=>"function", "identifier"=>"function", "options"=>{"managementExperience"=>"cli"}, "features"=>{"argo"=>nil, {"name"=>"App Link
                                    Runtime Parameters", "identifier"=>"app_link_runtime_params", "options"=>{"managementExperience"=>"custom"}, "features"=>{"argo"=>nil, {"name"=>"Coinstall Retail Apps", "identifier"=>"coinstall_retail_apps", 
                                   "options"=>{"managementExperience"=>"custom"}, "features"=>{"argo"=>nil, {"name"=>"Produces Sales", "identifier"=>"produces_sales_extension", "options"=>{"managementExperience"=>"custom"}, "features"=>{"argo"=>nil, {"name"=>"Checkout Post Purchase", 
                                   "identifier"=>"checkout_post_purchase", "options"=>{"managementExperience"=>"cli"}, "features"=>{"argo"=>{"surface"=>"checkout"}, {"name"=>"Checkout Extension", "identifier"=>"checkout_ui_extension", "options"=>{"managementExperience"=>"cli"}, 
                                   "features"=>{"argo"=>{"surface"=>"checkout"}, {"name"=>"Merchandising - Create Publication", "identifier"=>"merchandising_create_publication", "options"=>{"managementExperience"=>"custom"}, "features"=>{"argo"=>nil, {"name"=>"Merchandising - Fulfillment
                                    Variant Details", "identifier"=>"merchandising_fulfillment_variant_details", "options"=>{"managementExperience"=>"custom"}, "features"=>{"argo"=>nil, {"name"=>"Product Subscription", "identifier"=>"subscription_management", 
                                   "options"=>{"managementExperience"=>"cli"}, "features"=>{"argo"=>{"surface"=>"admin"}, {"name"=>"Marketing Activity", "identifier"=>"marketing_activity_extension", "options"=>{"managementExperience"=>"dashboard"}, "features"=>{"argo"=>nil, {"name"=>"Web
                                    Pixel Extension", "identifier"=>"web_pixel_extension", "options"=>{"managementExperience"=>"cli"}, "features"=>{"argo"=>nil, {"name"=>"Online Store - App Theme Extension", "identifier"=>"theme_app_extension", "options"=>{"managementExperience"=>"cli"},
                                    "features"=>{"argo"=>nil, {"name"=>"Payment Gateway", "identifier"=>"payment_gateway", "options"=>{"managementExperience"=>"custom"}, "features"=>{"argo"=>nil, {"name"=>"Payments App - Redeemable ", "identifier"=>"payments_app_redeemable", 
                                   "options"=>{"managementExperience"=>"dashboard"}, "features"=>{"argo"=>nil, {"name"=>"Retail Cart Promotion", "identifier"=>"retail_cart_promotion", "options"=>{"managementExperience"=>"dashboard"}, "features"=>{"argo"=>nil, {"name"=>"Retail Product 
                                   Recommendation", "identifier"=>"retail_product_recommendation", "options"=>{"managementExperience"=>"dashboard"}, "features"=>{"argo"=>nil, {"name"=>"POS UI Extension", "identifier"=>"pos_ui_extension", "options"=>{"managementExperience"=>"cli"}, 
                                   "features"=>{"argo"=>{"surface"=>"point_of_sale"}, {"name"=>"Subscription Link", "identifier"=>"subscription_link", "options"=>{"managementExperience"=>"dashboard"}, "features"=>{"argo"=>nil]
2023-05-16 17:12:04 │ extensions │ DEBUG GET https://xxx.myshopify.com/admin/api/unstable/themes/131218047168.json with request_id: 8ca21049-5920-444d-871d-454cf0bcec96
2023-05-16 17:12:04 │ extensions │
2023-05-16 17:12:04 │ extensions │ --------- Pushing theme files to App Ext. Host (xxx) (#xxx) on xxx.myshopify.com
2023-05-16 17:12:04 │ extensions │ Pushing theme...     0%
2023-05-16 17:12:12 │ extensions │ DEBUG GET https://xxx.myshopify.com/admin/api/unstable/themes/131218047168/assets.json with request_id: edda2f4c-f07d-49b7-a06d-22461de6ffe5
2023-05-16 17:12:12 │ extensions │ Pushing theme...    40%
2023-05-16 17:12:12 │ extensions │ DEBUG [BulkJob #1880] job request: size=4, bytesize=15589
2023-05-16 17:12:13 │ extensions │ DEBUG PUT https://xxx.myshopify.com/admin/api/unstable/themes/131218047168/assets/bulk.json with request_id: 4a010195-7103-468f-ba7b-cf6e549c1a23
2023-05-16 17:12:13 │ extensions │ DEBUG [BulkJob #1880] bulk rest_request time: 954.704956ms
2023-05-16 17:12:13 │ extensions │ DEBUG [BulkJob #1880] job response: http_status=207
2023-05-16 17:12:13 │ extensions │ DEBUG [BulkJob #1880] bulk item success (item=sections/header-group.json)
2023-05-16 17:12:13 │ extensions │ Pushing theme...    60%
2023-05-16 17:12:13 │ extensions │ DEBUG [BulkJob #1880] bulk item success (item=templates/cart.json)
2023-05-16 17:12:13 │ extensions │ Pushing theme...    80%
2023-05-16 17:12:13 │ extensions │ DEBUG [BulkJob #1880] bulk item success (item=templates/product.json)
2023-05-16 17:12:13 │ extensions │ Pushing theme...   100%
2023-05-16 17:12:13 │ extensions │ DEBUG [BulkJob #1880] bulk item success (item=templates/index.json)
2023-05-16 17:12:13 │ extensions │ DEBUG [Bulk] shutdown, remaining_items=0
2023-05-16 17:12:13 │ extensions │ ------------------
2023-05-16 17:12:14 │ extensions │ DEBUG POST https://partners.shopify.com/api/cli/graphql with request_id: b75da56c-a4cb-4300-83bb-605b3566fbed
2023-05-16 17:12:14 │ extensions │ DEBUG {"data"=>{"app"=>{"id"=>"xxx", "title"=>"xxx", "apiKey"=>"xxx", "apiSecretKeys"=>[{"secret"=>"yyy"}], "appType"=>nil, "extensionRegistrations"=>[{"id"=>"xxx", 
                                   "type"=>"THEME_APP_EXTENSION", "uuid"=>"xxx", "title"=>"tracker-ext", "draftVersion"=>{"registrationId"=>"xxx", "context"=>nil, "lastUserInteractionAt"=>"2023-05-16T12:53:51-04:00", 
                                   "location"=>"https://partners.shopify.com/xxx/apps/yyy/extensions/theme_app_extension/yyy", "validationErrors"=>[], "id"=>"xxx", "uuid"=>"xxx", "versionTag"=>"0.0.0"]}
2023-05-16 17:12:14 │ extensions │
2023-05-16 17:12:14 │ extensions │ --------- Viewing extension…
2023-05-16 17:12:14 │ extensions │ Enable your theme app extension:
2023-05-16 17:12:14 │ extensions │ https://partners.shopify.com/xxx/apps/yyy/extensions/theme_app_extension/xxx
2023-05-16 17:12:14 │ extensions │
2023-05-16 17:12:14 │ extensions │ Setup your theme app extension in the host theme:
2023-05-16 17:12:14 │ extensions │ https://xxx.myshopify.com/admin/themes/131218047168/editor
2023-05-16 17:12:14 │ extensions │
2023-05-16 17:12:14 │ extensions │ Preview your theme app extension:
2023-05-16 17:12:14 │ extensions │ http://127.0.0.1:9292
2023-05-16 17:12:14 │ extensions │ ------------------
2023-05-16 17:12:14 │ extensions │ [2023-05-16 19:12:14] INFO  WEBrick 1.7.0
2023-05-16 17:12:14 │ extensions │ [2023-05-16 19:12:14] INFO  ruby 2.7.8 (2023-03-30) [x86_64-linux]
2023-05-16 17:12:14 │ extensions │ [2023-05-16 19:12:14] INFO  WEBrick::HTTPServer#start: pid=88355 port=9292
2023-05-16 17:12:15 │ extensions │ DEBUG POST https://partners.shopify.com/api/cli/graphql with request_id: b9fc3889-a05e-482a-8787-b63dfab9572a
2023-05-16 17:12:15 │ extensions │ DEBUG {"data"=>{"extensionUpdateDraft"=>{"extensionVersion"=>{"registrationId"=>"xxx", "context"=>nil, "lastUserInteractionAt"=>"2023-05-16T13:12:14-04:00", 
                                   "location"=>"https://partners.shopify.com/xxx/apps/yyy/extensions/theme_app_extension/xxx", "validationErrors"=>[]}, "userErrors"=>nil}
2023-05-16 17:12:15 │ extensions │ Pushed » 'tracker-ext' to a draft
2023-05-16 17:12:15 │ extensions │ - snippets/stars.liquid
2023-05-16 17:12:15 │ extensions │ - blocks/star_rating.liquid
2023-05-16 17:12:15 │ extensions │ - locales/en.default.json
2023-05-16 17:12:15 │ extensions │ - assets/thumbs-up.png
```

### Reproduction steps

1. yarn shopify app generate extension
2. yarn dev --tunnel ngrok
3. Go to https://xxxxxx.myshopify.com/admin/themes/131218047168/editor 

### Operating System

PopOS

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.45.4

**Comment by gonzaloriestra** [comment]
Hi!

I can't find anything wrong in the logs either. And it works for me. The star rating extension should appear when you click in `Add section`, is it not shown for you?

![22-27-iquk9-n8pun](https://github.com/Shopify/cli/assets/14979109/72ae8544-430e-4393-b44f-b0a21fac6a0f)

**Comment by gonzaloriestra** [comment]
These are the steps I followed, could you please try?
- `yarn create @shopify/app --template node`
- `yarn dev`
- Press `p` and install the app in your dev store
- `yarn shopify app generate extension --type theme_app_extension`
- `yarn dev`
- Enable theme app extension with the first link
- Open the second link and click on Add section

**Comment by sneakingJ** [comment]
This worked. So I guess the shop itself and the theme is working out.

What I did for this ticket was to integrate the extension into an already existing app, which did not run with the cli before. Maybe the current app is the issue? Cause right now, I created a new one for testing purposes.
What I am seeing though, is that I am missing the Dockerfile and the web folder in my first attempt. Are those two necessary?

**Comment by gonzaloriestra** [comment]
Great, I'm closing here, since the main issue has been solved.

As explained [here](https://shopify.dev/docs/apps/tools/cli/commands#deploy), the deploy command only uploads the extensions to Shopify, and you have to push your web app separately to Heroku (or wherever). Also, dev and deploy commands allow different environments, so you can use different Shopify apps.

Does this help? I'm not sure I understood your situation correctly 😅

**Comment by sneakingJ** [comment]
Yes, issue resolved. Thanks for your help! :)

So basically my current app is published already without any extensions, it's basically just using the admin api. But it does not use the cli yet. Now I need to develop a theme app extension for this app, which apparently HAS to use the cli. I'm just a bit confused as to how the rest of the app will be connected to this extension cli instance. So is deploying this extension (into our already existing app) possible without using the cli for the rest of it? Like what does the step "Building the app" actually do when deploying the extension? 
Does this make sense? :D Sorry, if it's confusing.

**Comment by manikandan-ravikumar** [comment]
Followed the same approach, but still my app is not listed under app blocks. Tried with multiple Online 2.0 themes but still no luck. I am using Shopify CLI 3.46.2 and node version v20.0.0. I created new Shopify app using `npm`, installed the app, generated new "Theme App Extension" following the [documentation](https://shopify.dev/docs/apps/online-store/theme-app-extensions/getting-started). I couldn't find star-rating app listed. Any help please!!

**Comment by alvaro-shopify** [comment]
Hi @manikandan-ravikumar. You need to install the app as well, you can do that following the `Preview URL` (click `p`) you can find at the footer of the dev console.
Maybe we should update the [documentation](https://shopify.dev/docs/apps/online-store/theme-app-extensions/getting-started) to include this additional step.
Please, let me know if this works for you
