### ISSUE TITLE
[Bug]: `shopify theme dev` is losing track of the development theme

### ISSUE THREAD

**Issue by karreiro** [Shopify/cli#3715]
### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

When users run `shopify theme dev`, a development theme should be created and assign as `[yours]` (your development theme should never be re-assigned).

### Actual behavior

When users run `shopify theme dev`, the development theme seems to be re-assigned and in some contexts the CLI is election even non-development themes.

**Comment by sameerxanand** [comment]
Here's how I'm working around it:

```bash
shopify theme list
```

Find your development theme in the list

```bash
shopify theme delete -t {ID of your development theme}
```

Run `shopify theme dev` and it should use a new development theme instead of the live theme.

---

Agree this whole issue has been a pain in the a**. Shopify pushed a new CLI update today which now shows a new warning:

```
Warning: Could not find ts-node at /opt/homebrew/Cellar/shopify-cli/3.59.0/libexec/lib/node_modules/@shopify/cli/dist/index-e6f8190d.js. Please ensure that ts-node is a devDependency. Falling back to compiled source.
```

**Comment by mgmanzella** [comment]
another example: https://github.com/Shopify/cli/issues/3794

**Comment by karreiro** [comment]
Thank you for sharing that context in the email, @davidhollenbeckx! That not only helps the team understand the issue itself, but it also helps us understand how developers use CLI in their workflows.

For anyone experiencing this problem, you can adopt the following steps as a temporary workaround:
- Run `shopify theme push -u -t <name_of_your_dev_theme>` to create a new theme
- Run `shopify theme dev -t <name_of_your_dev_theme>` to force the CLI to use that specific theme in the development server

As soon as we get this fixed, we will update this issue.

Thanks everyone for reporting this problem.

**Comment by karreiro** [comment]
Thank you, everyone, for reporting this problem and providing details.

This issue has been fixed by https://github.com/Shopify/cli/pull/3809, so upgrading to the latest release ([3.59.2](https://github.com/Shopify/cli/releases/tag/3.59.2)) fixes this problem.

**Comment by nboliver-ventureweb** [comment]
@karreiro This is definitely not fixed. See here: https://shopifypartners.slack.com/archives/CKQTKDZV2/p1714579081291059

**Comment by davidhollenbeckx** [comment]
@lukeh-shopify the issue will kick in after making a change to the theme and refreshing. there are loads of reproductions and logs in this thread.

also worth nothing it tends to show up randomly after a dev theme has been around for a bit - like, day two of a new theme build, I'll pull up the project to start working on it and the bug will appear again. next time it happens I'll screen record

I'm curious if you & the rest of the team at Shopify are testing this from a special shopify staff account, or if you've tried to reproduce in a regular vanilla partner account. last time this bug came up Shopify staff had a really hard time reproducing it even though thousands of partners were affected.

also not that it should matter, but I'm on the most recent version of the CLI with node 20. unix terminal

**Comment by tpage99** [comment]
Thanks @karreiro! This looks to have been resolved, or at least initially here pulling in and working on a handful of themes across different shops I'm not getting the issue.

Seems to be working as intended! Thanks so much for working on this 🙏

**Comment by faddies** [comment]
i am facing same issue but not in local environment but on live. i have other themes in my theme library and when i preview it, it giving me live site preview.

**Comment by EricWVGG** [comment]
I’m encountering this issue. Wound up getting around it by running a local HTTPS proxy. https://www.storyblok.com/faq/setup-dev-server-https-proxy
