### ISSUE TITLE
[Bug]: The contents of this file are auto-generated.

### ISSUE THREAD

**Issue by magify-expert-shopify** [Shopify/cli#4554]
### Please confirm that you have:

- [x] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [x] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

Nothing, just pull my content

### Actual behavior

I have this message in start of all my files after pulling.

```
/*
* ------------------------------------------------------------
* IMPORTANT: The contents of this file are auto-generated.
*
* This file may be updated by the Shopify admin theme editor
* or related systems. Please exercise caution as any changes
* made to this file may be overwritten.
* ------------------------------------------------------------
*/
```
The message is written multiple times, it's spam.

### Verbose output

shopify theme dev --legacy

### Reproduction steps

1. Pull with shopify cli

### Operating System

Windows 11

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.67.3

### Shell

PowerShell

### Node version (run `node -v` if you're not sure)

v22.5.1

### What language and version are you using in your application?

ruby 3.0.6p216 (2023-03-30 revision 23a532679b) [x64-mingw32]

**Comment by karreiro** [comment]
👋 Hey @magify-expert-shopify,

Thank you for reporting this!

As @rcasimmons mentioned, the headers are expected behavior; they clarify which files may be auto-updated by Shopify and may lose comments and user-defined spaces.

However, they shouldn't be duplicated when pulling, as you shared. I'm investigating this issue, and I will mark this as fixed once it gets resolved.

Thanks again for reporting this!

**Comment by AndrieseiMiruna** [comment]
Same issue, I am not using `--theme-editor-sync`, but sometimes I need to run `shopify theme pull -d` to get one small change from the customizer. And I get a lot of frustrating unreal changes
![Image](https://github.com/user-attachments/assets/6c66655e-d9c8-423d-9518-1171c14e03b9)

**Comment by karreiro** [comment]
👋 Hey folks,

Headers no longer get duplicated. This issue has been resolved at the platform level, so no CLI upgrade is required.

Thank you for reporting this!

**Comment by miguel-dango** [comment]
> 👋 Hey folks,
> 
> Headers no longer get duplicated. This issue has been resolved at the platform level, so no CLI upgrade is required.
> 
> Thank you for reporting this!

The problem is still in windows.

![Image](https://github.com/user-attachments/assets/b4c34919-0f5a-4198-868e-3d3e76608a91)

And I have the latest version of Shopify CLI at the moment

![Image](https://github.com/user-attachments/assets/2d99236d-b16b-45cf-b1a7-20e22e3962bb)
