### ISSUE TITLE
[Bug]: Shopify CLI (v3.70.0) Bug: Settings Not Updating Without Multiple Saves

### ISSUE THREAD

**Issue by shopify-development-code** [Shopify/cli#5037]
### Please confirm that you have:

- [x] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [x] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

It should save and synced every time.

### Actual behavior

We are encountering an issue where settings only appear after saving the file multiple times, which significantly disrupts our workflow. Each time we make changes, we have to repeatedly save the file to reflect the updates, which is both time-consuming and frustrating.

This issue persists across **multiple development environments**, and we are confident that it stems from the **Shopify CLI**. We are currently using the latest **version (3.70.0)** of the CLI, but the problem remains unresolved.

We would appreciate a resolution or guidance on addressing this issue to streamline our development process.

Repro steps: See attached screencast:
https://github.com/user-attachments/assets/e72d0a38-ee23-4987-a34f-cecc4400b707

See below screenshot, all times files are saved but not synced with editor:
![Image](https://github.com/user-attachments/assets/279765fd-fd30-429f-b9ab-2a71f9044893)

Here it is our environment for development:

[environments.dev]
store = "store-name"
password  = "shptka_token"
theme-editor-sync = true

### Verbose output

<details>
  <summary>shopify theme dev -e dev</summary>

  ```
  Files are not being saved and synced with editor on single save. But on terminal its showing files are synced correctly.
  ```

</details>

### Reproduction steps

1.Repro steps: See attached screencast:
https://github.com/user-attachments/assets/e72d0a38-ee23-4987-a34f-cecc4400b707

### Operating System

Windows 10, Windows 11

### Shopify CLI version (`shopify --version`)

3.70.0

### Node version (run `node -v` if you're not sure)

v22.12.0

**Comment by catlee** [comment]
I believe this should have been fixed by #5042

**Comment by frandiox** [comment]
>I believe this should have been fixed by https://github.com/Shopify/cli/pull/5042

That fix was released in [3.72.0](https://github.com/Shopify/cli/releases/tag/3.72.0) today. Can you try it @shopify-development-code ?

**Comment by kyrylo-soulandwolf** [comment]
@frandiox @catlee  This is still a problem.
Only in my case the problem with hot-reloading a CSS file. It needs to be saved twice for the CSS to take effect.
I'm happy to open a new issue if it's not the same as this one.
I tested it on a fresh Dawn theme with CLI 3.73.2.

To reproduce:

- Run `shopify theme dev`
-  Add anything to a CSS file
-  Save once

Result:
- Console shows `[HotReload] Event data: {type: 'css', key: 'assets/base.css'}`
- New CSS not applied

**Comment by jamesmengo** [comment]
Hey @shopify-development-code 

I haven't been able to reproduce this, so I may need your help diagnose the cause.

Could you please try the following on the **latest version**:
- Run the `theme dev` command with `--verbose` logs and share them here
- Upload the theme in question to your development shop and provide me with the:
  - development shop name (`xxxx.myshopify.com`)
  - theme name
