### ISSUE TITLE
[Bug]: The "Cookie banner" keeps appearing after every reload in the localhost server

### ISSUE THREAD

**Issue by karreiro** [Shopify/cli#5186]
The "Cookie banner" keeps appearing after every reload on the localhost server.

### Expected behavior

The "Cookie banner" should not appear after every reload on the localhost server:

![Image](https://github.com/user-attachments/assets/6ff14778-c5b2-46c8-b19a-0445dc3620fd)

### Actual behavior

It should work just like the preview URL.

### Reproduction steps

- Activate the banner at `/settings/privacy/consent-banner`
- Clone Dawn using `shopify theme init`
- Run `shopify theme dev`
- Notice it keeps appearing after every refresh

**Comment by ranjan-purbey** [comment]
The issue is not with the CLI but with the privacy banner itself. When a visitor tries to save their cookie preference by selecting either of the options, the cookie banner makes a POST request to **https**://127.0.0.1:9292/api/unstable/graphql.json.

Since the local dev server doesn't support SSL, the request fails and the user's preference is not saved.

As a workaround, you can prefix your local URL with `?pb=0` to keep the banner hidden.

**Comment by jo-ced** [comment]
Thanks, @Truja. Any news yet? The banner keeps showing up and it is super annoying. Especially in mobile view one has to click accept/decline every time as it blocks the whole view. Additionally, the cookie banner reappears with every HMR reload, forcing repeated interactions even after previous acceptance/rejection.

**Comment by ceri-waterscreative** [comment]
Temporary work-around listed here: 
https://community.shopify.dev/t/shopify-cookiebar-cannot-dismiss-pernamently-on-localdev-customizer/9479/5?u=ceri_waters

**Comment by lukecharle** [comment]
Any update on this @karreiro?

**Comment by jo-ced** [comment]
> Temporary work-around listed here: https://community.shopify.dev/t/shopify-cookiebar-cannot-dismiss-pernamently-on-localdev-customizer/9479/5?u=ceri_waters

Thank you so much @ceri-waterscreative. Your code snippet solves the issue.

I'll post it below in case the link stops working:
`liquid 
{%- if theme.role == "development" or request.design_mode -%}
    {% style %}
        #shopify-pc__banner {
            display:none!important;
        }
    {% endstyle %}
{%- endif -%}
`

**Comment by verdant-spark** [comment]
This is still happening - please keep this issue open and solve it!

**Comment by verdant-spark** [comment]
@Truja are you still to be looking at this? It's _so_ super annoying.

**Comment by Truja** [comment]
I just did a test and looks like the problem is fixed:
https://screenshot.click/07-46-p1c5t-l0oan.mp4

Please, let me know if you still notice it.

**Comment by MassimilianoLattanzio** [comment]
@Truja Nope, the issue is still there, as you can see here:
https://github.com/user-attachments/assets/c6c53ba0-af3f-4b85-bfbb-e0c702b0c240

I'm running `shopify theme dev` using the current latest version (3.83.3)

**Comment by verdant-spark** [comment]
@Truja - still present for me too. Also on 3.83.3

**Comment by Truja** [comment]
Oh, it is happening when you run the theme specifically ... 
Thanks @MassimilianoLattanzio @verdant-spark  I will test later today

**Comment by Truja** [comment]
@MassimilianoLattanzio @verdant-spark  Could you please retest ??
We merged a solution. Thanks

**Comment by MassimilianoLattanzio** [comment]
@Truja Not yet solved, unfortunately.
https://github.com/user-attachments/assets/bb750c83-636c-4df8-beed-b1e4b2a7ab60

I'm using `3.84.0` version

**Comment by plcdnl** [comment]
happens to me too. Any news?

**Comment by jacobgraf** [comment]
How is this not fixed yet? Very annoying.

**Comment by ygroenendijk** [comment]
Yep experiencing this (again)

**Comment by NeevusPeevus** [comment]
This has come up today on a ticket request from a merchant.

**Comment by ws-markb** [comment]
Just chiming in to say that yes, this issue is still happening. I even tried turning off the banner for my location in store settings, but that had no effect either.

**Comment by MassimilianoLattanzio** [comment]
Hey @Truja, can I assist you with fixing this? Is the related code available in one of your open source projects?

**Comment by ceri-waterscreative** [comment]
Boop.

**Comment by MassimilianoLattanzio** [comment]
Not yet solved, unfortunately

**Comment by verdant-spark** [comment]
Still an active bug

**Comment by MassimilianoLattanzio** [comment]
Finally, I had some time to investigate this issue.

The problem is that the `storefront-banner.js` file, which is responsible for the cookie banner functionality, determines whether to use `https` or `http` based on the following regex: `/^localhost(:|$)/`. However, the default host used by the `shopify theme dev` command is `127.0.0.1`, so the check fails because it matches only `localhost`, not the IP address.

To properly fix this, the regex should be updated to `/^(localhost|127\.0\.0\.1)(:|$)/`.

Unfortunately, this JS file is not part of this repository, so I wasn’t able to apply the fix directly. @Truja, could you help with this?  

As a temporary (and dumb) workaround, you can run the theme dev command while explicitly setting the host to `localhost`:
```bash
shopify theme dev --host localhost
```
This should resolve the issue.

**Comment by graygilmore** [comment]
@MassimilianoLattanzio thank you so much for your investigation! I've got a PR up now in the repo that owns this script that should resolve this for everyone. I'll keep this thread updated if it goes through.

**Comment by graygilmore** [comment]
The fix for this has been merged! It may take some time to propagate to all systems and for the cache to turn over. Let me know if you're still seeing issues in a few days.

**Comment by MassimilianoLattanzio** [comment]
Thank you @graygilmore!

**Comment by MassimilianoLattanzio** [comment]
Hey @graygilmore, unfortunately the issue is not yet fixed. There are two different checks for the localhost regex, but only one of them is updated.


The updated one:
```javascript
return t = /^(localhost|127\.0\.0\.1)(:|$)/.test(this.domain || "") ? "http" : "https",
```

The unfixed one:
```javascript
r = (/^localhost(:|$)/.test(c) ? "http:" : "https:") + "//" + c + "/api/unstable/graphql.json",
```

**Comment by graygilmore** [comment]
Very weird, this worked in local testing. I'll update the other one, too!

**Comment by graygilmore** [comment]
This should be resolved now, thanks for your patience everyone!

**Comment by MassimilianoLattanzio** [comment]
It works fine now! Thank you so much for your help @graygilmore

**Comment by Wakil18** [comment]
How do I set my theme role to development?

`theme.role == "development"`

**Comment by MassimilianoLattanzio** [comment]
@Wakil18 In theory, it should already be set while running the `shopify theme dev` command. Search for the JS `Shopify.theme` object and it should already contain `"role":"development"`
