### ISSUE TITLE
[Bug]: Being signed out randomly on CLI 3.80.0

### ISSUE THREAD

**Issue by keiraarts** [Shopify/cli#5826]
### Please confirm that you have:

- [x] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [x] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

On the latest version of the Shopify CLI, I am being signed out halfway through the process of uploading a large number of extensions. This happens at random, at various lengths of completion of my extension code, and there is no interactive prompt to sign-in after Shopify fails an authentication.

### Actual behavior

On Shopify CLI version 3.75.4 I can not re-create the issue of being signed out randomly during deployment.
npm install -g @shopify/cli@3.75.4

### Verbose output

<details>
  <summary>Verbose output</summary>

  ```
  successfully for extension: admin-product-block
21:23:25 │ customer-segment-edited-o │ Draft updated
successfully for extension: customer-segment-edited-orders

─────────────────────────────────────────────────────

› Press d │ toggle development store preview: ✔ on
› Press g │ open GraphiQL (Admin API) in your browser
› Press p │ preview in your browser
› Press q │ quit

Preview URL: https://therapeutic-everything-statement
-mc.trycloudflare.com/extensions/dev-console
GraphiQL URL: http://localhost:3457/graphiql

file:///Users/keiraclimson/.nvm/versions/node/v22.11.0/lib/node_modules/@shopify/cli/dist/index.js:218890
        if (!(a2 instanceof y)) throw a2;
                                ^

AbortError: The currently available CLI credentials are invalid.

2025-05-18T01:31:17.258Z: Request to https://partners.shopify.com/api/cli/graphql completed in 21365 ms
With response headers:
 - content-type: text/html
    
╭─ error ───────────────────────────────────────────╮
│                                                   │
│                                                   │
│  The Partners GraphQL API responded               │
│  unsuccessfully with the HTTP status 502 and      │
│  errors:                                          │
│                                                   │
│  {}                                               │
│                                                   │
│                                                   │
╰───────────────────────────────────────────────────╯

error Command failed with exit code 1.
  ```

</details>

### Reproduction steps

1. Sign-in to the CLI on the latest version.
2. Attempt to upload a 100 Shopify extensions which Shopify takes about 500ms per extension to upload.
3. After 30-50 seconds you will be signed out at random.

Is there a limit for the authentication token and Shopify expires the token faster than it can upload all of the extensions?

### Operating System

Mac OS

### Shopify CLI version (`shopify --version`)

3.8.0

### Shell

Bash

### Node version (run `node -v` if you're not sure)

v22

### What language and version are you using in your application?

Typescript

**Comment by gonzaloriestra** [comment]
Hi! Thanks for reporting the issue.

We introduced a new error handling mechanism in 3.80.0 and something is not working well. We will release a new patch version soon fixing it. In the meanwhile, you can use any previous version. Sorry for the inconvenience!

**Comment by gonzaloriestra** [comment]
@BearKid the latest version (3.80.1) should improve it, but we are still working on a better solution for the problem.

**Comment by joshreeves** [comment]
This is still an issue on the latest version (3.80.7).

**Comment by gonzaloriestra** [comment]
A proper fix will be released next week. If anyone wants to try, it's included in the latest nightly version: `npm i -g @shopify/cli@nightly`

**Comment by keiraarts** [comment]
Nightly is much better! Thank you for your efforts @gonzaloriestra

**Comment by ayushsoni1001** [comment]
Nightly is better but does not solve the issue, still happening on `0.0.0-nightly-20250610101758`

**Comment by gonzaloriestra** [comment]
@ayushsoni1001 could you please provide more details? Ideally a verbose log. Are you being signed out as well?

**Comment by ayushsoni1001** [comment]
There are no logs before it asks to login again and it needs me to enter the email and password again in the browser.

Not sure if this helps, but I managed to get these after authenticating it, do you see anything unusual here?

```bash
2025-06-11T11:24:39.717Z: Running command app dev
2025-06-11T11:24:39.719Z: Running system process in background:
  · Command: /Users/ayush/.nvm/versions/node/v22.13.1/bin/node /Users/ayush/.nvm/versions/node/v22.13.1/bin/shopify notifications list --ignore-errors
  · Working directory: /Users/ayush/tobi

2025-06-11T11:24:39.724Z: Notifications to show: 0
2025-06-11T11:24:39.731Z: Reading cached app information for directory /Users/ayush/tobi...
2025-06-11T11:24:39.732Z: Reading the content of file at shopify.app.toml...
2025-06-11T11:24:39.734Z: Reading the content of file at shopify.app.toml...
2025-06-11T11:24:39.736Z: Ensuring that the user is authenticated with the Partners API with the following scopes:
[]

2025-06-11T11:24:39.736Z: Getting session store...
2025-06-11T11:24:39.736Z: Validating existing session against the scopes:
[
  "openid",
  "https://api.shopify.com/auth/shop.admin.graphql",
  "https://api.shopify.com/auth/shop.admin.themes",
  "https://api.shopify.com/auth/partners.collaborator-relationships.readonly",
  "https://api.shopify.com/auth/shop.storefront-renderer.devtools",
  "https://api.shopify.com/auth/partners.app.cli.access",
  "https://api.shopify.com/auth/destinations.readonly",
  "https://api.shopify.com/auth/organization.store-management",
  "https://api.shopify.com/auth/organization.apps.manage"
]
For applications:
{
  "partnersApi": {
    "scopes": []
  }
}

2025-06-11T11:24:39.737Z: - Token validation -> It's expired: false
2025-06-11T11:24:39.737Z: The current session is valid but needs refresh. Refreshing...
2025-06-11T11:24:39.737Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=refresh_token
```

After this it goes on calling the refresh token api a few times

**Comment by ayushsoni1001** [comment]
I opened the issue on the dev community earlier explaining the same https://community.shopify.dev/t/shopify-cli-repeatedly-requires-authentication-frequent-logouts-and-2fa-prompts-v3-80-7/17055

**Comment by gonzaloriestra** [comment]
The original issue should be fixed in 3.81.0.

@ayushsoni1001 we will continue investigating your problem in the community forum.

**Comment by sebszocinski** [comment]
This is still an issue. I'm having to re-auth almost every time I step away for longer than 10 minutes. We need a better solution this is going to drive developers nuts! The token should at least last a whole day.
