### ISSUE TITLE
[Bug]: unable to get local issuer certificate

### ISSUE THREAD

**Issue by hasanaltun** [Shopify/cli#5858]
### Please confirm that you have:

- [x] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [x] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

The ‎`shopify theme dev` command should start the local development server and connect to my store without any issues.

### Actual behavior

I am experiencing an error when I run the ‎`shopify theme dev` command using the Shopify CLI. The command fails to connect to my store and shows an “unable to get local issuer certificate” error.

![Image](https://github.com/user-attachments/assets/ffa8927e-2723-4b96-a2b1-42823d81bc28)

### Verbose output

<details>
  <summary>Verbose output</summary>

  ```
  Paste the output here!
  ```

</details>

### Reproduction steps

 1. Run ‎`shopify theme dev`
 2. Wait for the CLI to connect to the store
 3. The error appears

### Operating System

macOS Sequoia

### Shopify CLI version (`shopify --version`)

3.80.1

### Node version (run `node -v` if you're not sure)

v23.11.0

**Comment by padronpedro** [comment]
Same Issue after upgrading to Shopify-cli v3.80.1, I'm on a Mac 15.4.1  node v23.11.0

I tried to downgrade to v3.77.1, but I got the same. I installed shopify-cli with Homebrew and yarn, and I got the same error

error
Request to https://xxxxxxxx.myshopify.com/password failed, reason: unable to get local issuer certificate

The password is right, this is happening with other stores that we have with password enabled

With a store without a password, when I open 127.0.0.1:9292 some images are not displayed, getting a 502 Bad Gateway

If I open the customizer, all images are fine, also using the preview mode.

**Comment by seanhopkins** [comment]
Same Issue after upgrading to Shopify-cli v3.80.1, I'm on a Mac 15.5 node v23.11.0

**Comment by domb182** [comment]
Same.

**Comment by iljamm** [comment]
ok so having switching to 3.78.1 I no longer see this certificate related error but now I am getting this Shopify error and I am not logged in as a partner, just a normal staff account. It worked all fine prior to updating to 3.80.2 today.

```
╭─ error ──────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                              │
│  You are not authorized to use the CLI to develop in the provided store.                     │
│                                                                                              │
│  You can't use Shopify CLI with development stores if you only have Partner staff member     │
│  access. If you want to use Shopify CLI to work on a development store, then you should be   │
│  the store owner or create a staff account on the store.                                     │
│                                                                                              │
│  If you're the store owner, then you need to log in to the store directly using the store    │
│  URL at least once before you log in using Shopify CLI.Logging in to the Shopify admin       │
│  directly connects the development store with your Shopify login.                            │
│                                                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────╯

```

**Comment by iljamm** [comment]
> Hi all -- thanks for raising. Can you check:
> 
> * using a homebrew installed CLI (`brew install ...`) the fact that most are on Mac here makes this a possibility
> * presuming you have homebrew installed -- even if not installing the shopify CLI via it -- can you check the date on `brew list ca-certificates`
> * and, can you reach the site(s) in question with your browser (presumably yes)
> 
> Thank you -

All good in browser.

For me brew list ca-certificates returned:

/usr/local/Cellar/ca-certificates/2025-05-20/sbom.spdx.json
/usr/local/Cellar/ca-certificates/2025-05-20/share/ca-certificates/cacert.pem

Initially I had shopify-cli installed with Homebrew but then during a troubleshooting session I switched to npm installation.

**Comment by seanhopkins** [comment]
@shauns - 
Yep, sites can be reached in browser, cert dates:

/opt/homebrew/Cellar/ca-certificates/2025-05-20/sbom.spdx.json
/opt/homebrew/Cellar/ca-certificates/2025-05-20/share/ca-certificates/cacert.pem

**Comment by AaronBarcos** [comment]
If you want to skip SSL certificate validation temporarily:

`NODE_TLS_REJECT_UNAUTHORIZED=0 shopify theme dev`

This worked for me for the latest version as well

**Comment by padronpedro** [comment]
> If you want to skip SSL certificate validation temporarily:
> 
> `NODE_TLS_REJECT_UNAUTHORIZED=0 shopify theme dev`
> 
> This worked for me for the latest version as well

This works for me (using v3.80.4 via homebrew), of course, it's a temporary solution, but at least we can work for the moment, thanks @AaronBarcos

**Comment by anastis** [comment]
Probably a duplicate / same issue as #5376

**Comment by vit0rr** [comment]
> Thanks all for your patience. Investigation is ongoing. You can also try switching to an `nvm` managed NodeJS. This seems to resolve the certificate issue.

Yeah, it worked, thank you! 

> nvm use 18

**Comment by shauns** [comment]
Pleased to share that this should now be resolved. Apologies again for the interruption in service.

**Comment by nikitaourazbaev** [comment]
> Pleased to share that this should now be resolved. Apologies again for the interruption in service.

Happy to report it works here!

**Comment by padronpedro** [comment]
@shauns 

Unfortunately, it worked the first time, then I closed the terminal and opened a new one, ran the Shopify theme dev again, and the error is back

**Comment by padronpedro** [comment]
> [@padronpedro](https://github.com/padronpedro) exact same error in the second terminal? Something about an issuer certificate?

I tried again with different projects, and it's working fine now.

**Comment by hasanaltun** [comment]
it's works. thanks for the update.
