### ISSUE TITLE
[Issue]: Local Changes not updating

### ISSUE THREAD

**Issue by dbzx10299** [Shopify/cli#744]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Other

### Expected behavior

I am working on a shopify theme. The theme is hooked up to github and on the shopify admin, the theme is connected to github. I am working on my theme with the shopify cli and I have a global js file.

The theme is being served with `shopify theme dev` command.

For this example lets call it `theme.js`.

If I make any change inside of theme.js, it's all good, these changes are reflected. If I create another file under `assets`, `foo.js` and export a function, I can dynamically import it into the theme.js file based on a user action. However, any additional changes to `foo.js` will not be reflected ever.

In order to fix this, I have to go on Users/user/.cache/shopify and delete the .db.pstore file.

If I had a file like this and made a mistake, I would see that error in the console when the function is run. Now that the foo.js file is created, when I fix my obvious mistake, it will continue to log 'arrr ' is not defined. If I look at the error link it will show me the foo.js file and nothing is shown to be updated, even though on my machine the file is indeed updated.
```js
// in foo.js
export function foo() {
  const arr = [1, 2, 3]
  // make a spelling mistake
 console.log(arrrr.length)
}

// in theme.js
btn.addEventListener('click', async e => {
  const { foo } = await import('./foo.js')
  foo()
})
```

### Actual behavior

On page refresh, changes are not reflected

### Reproduction steps

1. Create javascript file under theme/assets
2. Export a function from this new js file
3. Use a dynamic import statement in the theme.js file. Any additional changes after the file is created will not be reflected.

### Operating System

Mac OS Monterey

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.22.1

### Shell

zsh

### Node version (run `node -v` if you're not sure)

18.12.0

### What language and version are you using in your application?

javascript

**Comment by Poitrin** [comment]
I haven't been able yet to reproduce this issue.
With

- `<script src="{{ 'theme.js' | asset_url }}" defer="defer"></script>` in my `theme.liquid` file,
- and files `foo.js` in `theme.js` in `assets` folder

the page always refreshed and loaded the correct code when I updated `foo.js`.
However, I will try again as soon as #1119 has been fixed.

```js
// foo.js
export function foo() {
  console.log('----------\nfoo----------')
  const arr = [1, 2, 3]
  // make a spelling mistake
  console.log(arrrrr.length)
}

// theme.js
document.getElementsByTagName('body')[0].addEventListener('click', async (e) => {
  console.log('============\nHELLO\n============\n')
  const {foo} = await import('./foo.js')
  foo()
})
```

**Comment by dbzx10299** [comment]
Sorry, I missed that. In my case I had a js error, and I fixed it and the console kept throwing an error and when I would look at the src pane, it kept showing the old file contents. I restarted the server and it persisted until I actually renamed the asset file. It‘s like it kept pointing the the old version of the file

**Comment by Poitrin** [comment]
I tried it again after #1119 being fixed, but could still not reproduce your bug.
Here are the steps I did:
1. `shopify theme init` new theme
2. `shopify theme dev --path="./new-theme"`
3. Add `assets/foo.js` with
```js
export function foo() {
  const arr = [1, 2, 3]
  console.log(arr.length)
}
```
4. In `sections/announcement-bar.liquid`:
```diff
        {%- endif -%}
      </div>
  {%- endcase -%}
{%- endfor -%}

+ <script>
+  document.getElementsByTagName('body')[0].addEventListener('click', async (e) => {
+     const {foo} = await import('{{ 'foo.js' | asset_url }}')
+     foo()
+   })
+ </script>

{% schema %}
{
  "name": "t:sections.announcement-bar.name",
  "max_blocks": 12,
  "class": "announcement-bar-section",
```
5. Open `http://127.0.0.1:9292/`
6. Click around and make sure that `3` is displayed in browser console
7. Update `foo.js`, e.g. by adding invalid code
8. Make sure to see `[HotReload] Refreshing entire page` in browser console, if you preserve the log.
9. Click around again and make sure that the error is displayed in the browser console

Do you want to share your theme code (only needs to be the bare minimum to reproduce the bug), so that I can take a closer look?

**Comment by dbzx10299** [comment]
Thanks for looking into this. I don't know why it's working on your end but typically I am a vue developer and moved over to a headless solution using nuxt. I got very irritated with the shopify cli and my code is not working anymore for the cli.  When I ran into this issue I uninstalled the shopify cli globally and reinstalled it and that fixed it but when I used dynamic imports, then any further file changes were not showing. Maybe it was a weird cache issue on my machine. If it worked for you then something on my end must be off
